"""Arch live installer platform modules."""

from .discovery import (
    HandoffDiscoveryError,
    HandoffDiscoveryResult,
    HandoffValidationContext,
    build_validation_context_from_runtime,
    discover_and_validate_handoff_plan,
    discover_handoff_sources,
    enumerate_ventoy_data_partitions,
    load_runtime_metadata,
    open_validated_handoff,
)
from .identity import (
    IdentityMatchResult,
    LsblkProbe,
    MachineIdentityError,
    match_machine_identity,
)
from .preflight import PreflightGateError, PreflightSummary, assert_preflight_ready, build_preflight_summary
from .network import (
    NetworkFallbackError,
    NetworkManagerClient,
    NetworkReadiness,
    NetworkResolutionResult,
    SystemConnectivityProbe,
    assert_network_ready,
    resolve_network_connectivity,
)
from .boot_policy import (
    BootPolicyError,
    BootPolicySummary,
    assert_boot_policy_ready,
    discover_boot_entries,
    discover_boot_order,
    summarize_boot_policy,
    verify_limine_efi_assets,
    verify_windows_efi_assets,
)
from .install import (
    DEFAULT_LIVE_STAGE_ROOT,
    LiveInstallError,
    LiveInstallExecutionResult,
    cleanup_live_stage,
    execute_install_plan,
    resolve_live_stage_root,
    stage_live_runtime_artifact,
)

__all__ = [
    "HandoffDiscoveryError",
    "HandoffDiscoveryResult",
    "HandoffValidationContext",
    "build_validation_context_from_runtime",
    "discover_and_validate_handoff_plan",
    "discover_handoff_sources",
    "enumerate_ventoy_data_partitions",
    "IdentityMatchResult",
    "LsblkProbe",
    "DEFAULT_LIVE_STAGE_ROOT",
    "LiveInstallError",
    "LiveInstallExecutionResult",
    "load_runtime_metadata",
    "open_validated_handoff",
    "MachineIdentityError",
    "PreflightGateError",
    "PreflightSummary",
    "NetworkFallbackError",
    "NetworkManagerClient",
    "NetworkReadiness",
    "NetworkResolutionResult",
    "SystemConnectivityProbe",
    "assert_network_ready",
    "BootPolicyError",
    "BootPolicySummary",
    "assert_boot_policy_ready",
    "discover_boot_entries",
    "discover_boot_order",
    "assert_preflight_ready",
    "build_preflight_summary",
    "cleanup_live_stage",
    "execute_install_plan",
    "match_machine_identity",
    "resolve_network_connectivity",
    "summarize_boot_policy",
    "verify_limine_efi_assets",
    "verify_windows_efi_assets",
    "resolve_live_stage_root",
    "stage_live_runtime_artifact",
]
