"""Build the disposable dual-boot GPT disk and Ventoy handoff USB fixture.

Geometry intentionally matches `rebuild/assets/templates/plan.template.json`
(the same fixture already exercised by `test_windows_handoff.py`), so the
authenticated handoff plan generated by `plan_fixture.py` can reuse those
proven-valid GPT bounds and GUIDs verbatim.
"""

from __future__ import annotations

import dataclasses
import subprocess
import time
from dataclasses import dataclass
from pathlib import Path

from .plan_fixture import DiskGeometry


LOGICAL_SECTOR_SIZE = 512
DISK_SIZE_BYTES = 512 * 1024**3  # 549755813888, matches the shipped plan template
GPT_DISK_GUID = "00000000-0000-4000-8000-000000000010"
ESP_PARTITION_GUID = "00000000-0000-4000-8000-000000000011"
WINDOWS_PARTITION_GUID = "00000000-0000-4000-8000-000000000012"

ESP_START_SECTOR = 2048
ESP_END_SECTOR = 1050623
WINDOWS_START_SECTOR = 1050624
WINDOWS_END_SECTOR = 943718399
FREE_START_SECTOR = 943718400
FREE_END_SECTOR = 1027604479

SYNTHETIC_WINDOWS_EFI_CONTENT = (
    b"OMARCHY-VM-TEST-SYNTHETIC-WINDOWS-BOOTMGR\x00"
    b"This file stands in for a real Windows boot manager EFI binary so the\n"
    b"installer's Windows-EFI-preservation invariant can be exercised end to\n"
    b"end on a disposable VM disk. It is not a real Microsoft binary.\n"
)


def geometry() -> DiskGeometry:
    return DiskGeometry(
        gpt_disk_guid=GPT_DISK_GUID,
        disk_size_bytes=DISK_SIZE_BYTES,
        logical_sector_size=LOGICAL_SECTOR_SIZE,
        disk_model="",
        disk_serial="",
        esp_start_sector=ESP_START_SECTOR,
        esp_end_sector=ESP_END_SECTOR,
        esp_size_bytes=(ESP_END_SECTOR - ESP_START_SECTOR + 1) * LOGICAL_SECTOR_SIZE,
        esp_partition_guid=ESP_PARTITION_GUID,
        esp_filesystem_uuid="",
        windows_start_sector=WINDOWS_START_SECTOR,
        windows_end_sector=WINDOWS_END_SECTOR,
        windows_size_bytes=(WINDOWS_END_SECTOR - WINDOWS_START_SECTOR + 1) * LOGICAL_SECTOR_SIZE,
        windows_partition_guid=WINDOWS_PARTITION_GUID,
        windows_filesystem_uuid="",
        free_start_sector=FREE_START_SECTOR,
        free_end_sector=FREE_END_SECTOR,
        free_size_bytes=(FREE_END_SECTOR - FREE_START_SECTOR + 1) * LOGICAL_SECTOR_SIZE,
    )


def _run(command: list[str], **kwargs) -> subprocess.CompletedProcess[str]:
    return subprocess.run(command, capture_output=True, text=True, check=True, **kwargs)


@dataclass
class LoopHandle:
    device: str

    def partition(self, number: int) -> str:
        return f"{self.device}p{number}"


def _attach_loop(image_path: Path, *, partscan: bool = True) -> LoopHandle:
    args = ["losetup", "--show", "-f"]
    if partscan:
        args.append("-P")
    args.append(str(image_path))
    device = _run(args).stdout.strip()
    return LoopHandle(device)


def _detach_loop(handle: LoopHandle) -> None:
    for _ in range(5):
        try:
            _run(["losetup", "-d", handle.device])
            return
        except subprocess.CalledProcessError:
            time.sleep(1)
    _run(["losetup", "-d", handle.device])


def _wait_for_partitions(handle: LoopHandle, count: int, *, timeout: float = 45.0) -> None:
    """Loop-device partition-scan under WSL2's kernel is flaky/slow; retry through
    several independent rescan mechanisms rather than trusting any single one."""
    deadline = time.monotonic() + timeout
    attempt = 0
    while time.monotonic() < deadline:
        attempt += 1
        for rescan in (
            ["partprobe", handle.device],
            ["partx", "-a", handle.device],
            ["blockdev", "--rereadpt", handle.device],
        ):
            subprocess.run(rescan, capture_output=True, text=True, check=False)
        subprocess.run(["udevadm", "settle", "--timeout=5"], capture_output=True, text=True, check=False)
        if all(Path(handle.partition(i)).exists() for i in range(1, count + 1)):
            return
        time.sleep(1.5)
    raise RuntimeError(f"Partitions did not appear for {handle.device} within {timeout}s")


def build_main_disk(disk_path: Path) -> DiskGeometry:
    """Create the disposable GPT disk: ESP + synthetic Windows + free extent."""
    geo = geometry()
    _run(["qemu-img", "create", "-f", "raw", str(disk_path), str(geo.disk_size_bytes)])

    handle = _attach_loop(disk_path)
    try:
        _run(["sgdisk", f"--disk-guid={GPT_DISK_GUID}", handle.device])
        _run(
            [
                "sgdisk",
                f"--new=1:{ESP_START_SECTOR}:{ESP_END_SECTOR}",
                "--typecode=1:ef00",
                "--change-name=1:EFI",
                f"--partition-guid=1:{ESP_PARTITION_GUID}",
                handle.device,
            ]
        )
        _run(
            [
                "sgdisk",
                f"--new=2:{WINDOWS_START_SECTOR}:{WINDOWS_END_SECTOR}",
                "--typecode=2:0700",
                "--change-name=2:WINDOWS",
                f"--partition-guid=2:{WINDOWS_PARTITION_GUID}",
                handle.device,
            ]
        )
        _run(["sgdisk", "--print", handle.device])
        _wait_for_partitions(handle, 2)

        esp_part = handle.partition(1)
        windows_part = handle.partition(2)

        _run(["mkfs.vfat", "-F", "32", "-n", "ESP", esp_part])
        _run(["mkfs.ntfs", "-Q", "-F", "-L", "WINDOWS", windows_part])
        _run(["udevadm", "settle", "--timeout=5"])
        esp_fs_uuid = _run(["blkid", "-s", "UUID", "-o", "value", esp_part]).stdout.strip()
        if not esp_fs_uuid:
            raise RuntimeError(f"Could not read the formatted ESP filesystem UUID for {esp_part}")
        geo = dataclasses.replace(geo, esp_filesystem_uuid=esp_fs_uuid)

        mount_point = disk_path.parent / "esp-mount"
        mount_point.mkdir(exist_ok=True)
        _run(["mount", esp_part, str(mount_point)])
        try:
            ms_boot = mount_point / "EFI" / "Microsoft" / "Boot"
            ms_boot.mkdir(parents=True, exist_ok=True)
            (ms_boot / "bootmgfw.efi").write_bytes(SYNTHETIC_WINDOWS_EFI_CONTENT)
            fallback = mount_point / "EFI" / "Boot"
            fallback.mkdir(parents=True, exist_ok=True)
            (fallback / "bootx64.efi").write_bytes(SYNTHETIC_WINDOWS_EFI_CONTENT)
        finally:
            _run(["umount", str(mount_point)])
    finally:
        _detach_loop(handle)

    return geo


def build_ventoy_disk(
    ventoy_path: Path,
    *,
    iso_path: Path,
    size_padding_bytes: int = 512 * 1024 * 1024,
) -> Path:
    """Create a single-partition FAT32 disk image labeled VENTOY, sized to also hold the ISO."""
    iso_size = iso_path.stat().st_size
    total_size = iso_size + size_padding_bytes
    _run(["qemu-img", "create", "-f", "raw", str(ventoy_path), str(total_size)])

    handle = _attach_loop(ventoy_path)
    try:
        _run(["sgdisk", "--new=1:2048:0", "--typecode=1:0700", "--change-name=1:VENTOY", handle.device])
        _wait_for_partitions(handle, 1)
        part = handle.partition(1)
        _run(["mkfs.vfat", "-F", "32", "-n", "VENTOY", part])

        mount_point = ventoy_path.parent / "ventoy-mount"
        mount_point.mkdir(exist_ok=True)
        _run(["mount", part, str(mount_point)])
        try:
            (mount_point / "omarchy").mkdir(exist_ok=True)
            iso_dest = mount_point / iso_path.name
            _run(["cp", "--reflink=auto", str(iso_path), str(iso_dest)])
        finally:
            _run(["umount", str(mount_point)])
    finally:
        _detach_loop(handle)

    return ventoy_path


def write_plan_files_onto_ventoy(
    ventoy_path: Path,
    write_files_callback,
) -> None:
    """Mount the Ventoy image, hand the mounted root to `write_files_callback`, unmount."""
    handle = _attach_loop(ventoy_path)
    try:
        _wait_for_partitions(handle, 1)
        part = handle.partition(1)
        mount_point = ventoy_path.parent / "ventoy-mount"
        mount_point.mkdir(exist_ok=True)
        _run(["mount", part, str(mount_point)])
        try:
            write_files_callback(mount_point, mount_point / iso_name_on(mount_point))
        finally:
            _run(["umount", str(mount_point)])
    finally:
        _detach_loop(handle)


def iso_name_on(mount_point: Path) -> str:
    candidates = sorted(mount_point.glob("*.iso"))
    if len(candidates) != 1:
        raise RuntimeError(f"Expected exactly one ISO on the Ventoy fixture, found {len(candidates)}")
    return candidates[0].name
